Repository SocialGouv/code-du-travail-backoffice, pull requests merged in 2020-01, with the labels that each got.

#832 fix(admin): force non-empty values for answers edition auto-draft status
  packages/contrib/pages/admin/answers/edit.js
Labels: :package: admin, :pushpin: bug

#836 feat(admin): sort generic answers list by question index
  packages/contrib/src/sagas/answers/load.js
Labels: :package: admin, :pushpin: enhancement

#844 fix(build): repair production start script env path
  scripts/prod/start.sh
Labels: :pushpin: bug

#845 fix(admin): remove agreements name shortening for generic answers
  packages/contrib/src/sagas/answers/load.js
Labels: :package: admin, :pushpin: bug

#846 feat(admin): allow answer question to be selected in edition
  packages/contrib/pages/admin/answers/edit.js
Labels: :package: admin, :pushpin: enhancement

#858 fix(build): install dependencies before everything else in prod
  scripts/prod/start.sh
Labels: :pushpin: bug

#859 fix(build): grant postgres kinto db privileges to default user
  package.json
  scripts/docker/db/create_kinto_database.sh
Labels: :pushpin: bug

#866 ci(github): configure todo bot
  .github/config.yml
Labels: :pushpin: tech

#865 fix(deps): resolve security vulnerability
  packages/contrib/.babelrc
  packages/contrib/package.json
  packages/contrib/pages/admin/answers/edit.js
  packages/contrib/pages/answers/view.js
  packages/contrib/src/blocks/Login/index.js
  packages/contrib/src/layouts/Header/index.js
  packages/contrib/src/layouts/Header/styles.js
  packages/contrib/src/svgs/Marianne.js
  packages/contrib/src/svgs/Welcome.js
  packages/contrib/src/svgs/marianne.svg
  packages/contrib/src/svgs/welcome.svg
  yarn.lock
Labels: :pushpin: security

#868 fix(build): add missing vars quotes in prod start script
  scripts/prod/start.sh
Labels: :pushpin: bug

#870 build(prod): optimize docker and yarn cache
  scripts/prod/start.sh
Labels: :pushpin: tech

#871 fix(build): dissociate docker ports logic
  .env.example
  docker-compose.yml
  features/support/world/index.js
  image.web.Dockerfile
  packages/api/Dockerfile
  packages/api/src/index.js
  packages/contrib/next.config.js
  scripts/prod/start.sh
Labels: :pushpin: bug

#872 fix(build): work around docker moby/moby #36573 issue
  .dockerignore
  image.web.Dockerfile
Labels: :pushpin: bug

#873 fix(build): simplify api and web ports logic
  docker-compose.yml
  image.web.Dockerfile
  packages/api/Dockerfile
  packages/api/src/index.js
  packages/contrib/next.config.js
  packages/contrib/server/index.js
Labels: :pushpin: bug

#874 fix(build): ignore local api node modules in docker
  packages/api/Dockerfile
  scripts/prod/start.sh
Labels: :pushpin: bug

#875 fix(seo): replace robot.txt by noindex meta to block referencing
  packages/api/.dockerignore
  packages/contrib/pages/_document.js
  packages/contrib/public/robots.txt
  packages/contrib/src/layouts/Main/index.js
Labels: :pushpin: bug

#876 fix(style): add missing css file
  .gitignore
  packages/contrib/.gitignore
  packages/contrib/public/static/css/socialgouv-bootstrap.min.css
Labels: :pushpin: bug

#883 chore(deps): update jest monorepo to v25 (major)
  packages/contrib/package.json
  packages/contrib/src/blocks/AnswerEditionContent/__tests__/__snapshots__/index.test.js.snap
  yarn.lock
Labels: :pushpin: tech

#884 fix(contrib): handle api uri env var dynamically
  docker-compose.yml
  image.web.Dockerfile
  packages/contrib/next.config.js
Labels: :pushpin: bug

#886 build(docker): switch to node v12.14.1-alpine
  image.master.Dockerfile
  image.web.Dockerfile
  packages/api/Dockerfile
Labels: :pushpin: tech

#887 build(docker): switch master to igabriele/knex-pg
  image.master.Dockerfile
Labels: :pushpin: tech

#888 fix(contrib): clean next document head
  packages/contrib/pages/_document.js
  packages/contrib/src/layouts/Main/index.js
Labels: :pushpin: bug

#889 fix(contrib): move head title into layout
  packages/contrib/src/layouts/Main/index.js
Labels: :pushpin: bug

#890 fix(data-filler): handle non-existing kinto uri env var
  packages/contrib/next.config.js
  packages/data-filler/src/kinto/client.js
Labels: :pushpin: bug

#891 style(contrib): isolate data-filler bootstrap css
  packages/contrib/pages/_document.js
  packages/contrib/pages/admin/data-filler/bucket/[bucket]/collection/[collection]/record/[record].js
  packages/contrib/pages/admin/data-filler/index.js
  packages/contrib/pages/admin/data-filler/themes/[source].js
  packages/contrib/public/static/css/socialgouv-bootstrap.min.css
  packages/contrib/src/layouts/DataFillerMain/index.js
Labels: :package: data-filler, :pushpin: tech

#892 fix(admin): remove non-existing agreement for generic answers
  packages/contrib/src/sagas/answers/loadOne.js
Labels: :package: admin, :pushpin: bug

#893 fix(data-filler): backport latest fixes
  packages/data-filler/scripts/fixUrl.js
  packages/data-filler/src/cdtn-api.js
  packages/data-filler/src/forms/CCN.js
  packages/data-filler/src/forms/components/CDTNReferences.js
  packages/data-filler/src/sources.js
Labels: :package: data-filler

#894 feat(admin): add published column to dashboard
  packages/contrib/pages/admin/index.js
  packages/contrib/src/components/Table.js
Labels: :package: admin

#897 fix(scripts): correct cache log in prod start
  scripts/prod/start.sh
Labels: :pushpin: bug
